### ISSUE TITLE
TODO: resource_redfish_storage_volume enhancements

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#5]
Just leaving here this issue to keep track of enhancements that need to be done in the **resource_redfish_storage_volume** resource.

**Comments**
- Always Immediate operations are preferred.
- This resource has not have implemented the read or update function since we cannot update a volume. To "update it" in some way, we would need to destroy and the recreate it. I think that's not a desired behavior here.  

**Things to do**  
- [ ] The validate function for settingsApplyTime needs to be implemented.  

- [ ] Better handling on OnReset operations. If a job is created using terraform, and then the server is restarted manually, the new volume will be there (if the job was successful). At this point, if a *terraform destroy* command is issued, it will look for the new volume and destroy it rightaway, without creating a job (this scenario might be buggy for controllers that does not support Immediate opperations).

- [ ] Since the iDRAC still doesn't support DELETE operation on standard tasks collection, tasks cannot be deleted in a standard way for all vendors. Here I had to implement the propietary way iDRAC manages jobs (*/redfish/v1/Managers/iDRAC.Embedded.1/Jobs/*) through the redfish API. This will change in the future as soon as iDRAC redfish implementation supports that, Function to do this is *common.DeleteDellJob*
